debug: true
# Default language
default-language: en
# Disable all metrics included in this plugin.
disable-metrics: false
# Whether or not resourcepack file hashes should be generated on startup:
autogeneratehashes: true
# Whether to append the pack hash to the end of the URL of the pack like url#hash.
# This is necessary to work around a Vanilla bug which prevents changed packs from being downloaded
# properly again: https://bugs.mojang.com/browse/MC-164316
append-hash-to-url: true
# Whether /usepack should apply packs temporary or permanent when run without any argument:
usepack-is-temporary: true
# Whether packs that a player has stored will override a matched assignments
stored-packs-override-assignments: false
# When manually setting a permanent pack then it will be reset if the user disconnects in under x amount of seconds.
# 0 or anything below will disable this functionality
permanent-pack-remove-time: 30
# Whether to hook into authentication plugins
# Currently supported: AuthMe, OpeNLogin and nLogin
use-auth-plugin: true
# Different packs can be defined in this section
packs:
  examplepack: 
    # The url the client should download the resourcepack from.
    # Has to be a direct download link! No mediafire/mega/other oneclick-hoster!
    url: http://example.com/lobbyresourcepack.zip
    # The sha1 hash of the resourcepack's zip file
    hash: abcdef012345678abcdef012345678abcdef0123
    # The format version of this resourcepack
    format: 1
    # Directly define the Minecraft version instead of the format
    # Supports string representation of the versions and protocol numbers
    # You don't need to define both the version and the format (if you do then the highest one will take effect)
    version: "1.8"
    # Whether this pack will only be sent to players with a certain permission
    # permission: worldresourcepacks.pack.<packname>
    restricted: false
    # If you want you can define a specific permission for this pack if you don't want
    # the default worldresourcepacks.pack.<packname> permission!
    permission: worldresourcepacks.pack.examplepack
  globalpack:
    url: http://example.com/globalpack.zip
    hash: abcdef012345678abcdef012345678abcdef0123
  gamepack:
    # Set different variants e.g. for different versions or permissions
    # This list supports all normal pack settings and is checked top to bottom.
    # The first one that matches the player will be used.
    variants:
    - url: http://example.com/minigameresourcepack_1_15.zip
      hash: 012345678abcdef012345678abcdef012345678a
      version: '1.15'
    - url: http://example.com/minigameresourcepack_1_12.zip
      hash: 012345678abcdef01234567dddcdef012345678a
      version: '1.12'
  # Define as many packs as you want
  another_example_pack:
    url: http://example.com/another.zip
    hash: abcdef012345678abcdef012345678abcdef0123
# Empty pack to reset the pack to the default one
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  pack: globalpack
  # List of packs to not replace if the user already has them
  # If no main pack is set the first one also gets used to reset 
  # the pack if the user has a non-optional one
  # Also this list will be used to select a pack if a user does not have the permission
  # or the right version to use that pack. (From top to bottom)
  #optional-packs:
  #- examplepack2
  # Delay in ticks before sending the pack to a player after he logs in/switches to the world
  send-delay: 10
# Different worlds with different packs can be defined here
worlds:
  # Config for a world named "your_example_world"
  your_example_world:
    # You can define multiple packs starting with 1.20.3
    # On versions prior to it only the first pack will be used
    packs:
    - examplepack
    - globalpack
    #optional-packs:
    #- examplepack2
  your_example_nether:
    pack: examplepack2
    # Use a regex to target all worlds with a certain name
    regex: 'example_nether_.*'
  # Define as many worlds as you want.
  # The name of the section is the world name unless a regex is specified.
  another_example_world:
    pack: another_example_pack
